name: CloudFlare R2 Upload

on: [push, workflow_dispatch]

jobs:
  sync-r2:
    name: Upload to R2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mchangrh/s3cmd-sync@v1.1
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_ACCESS_KEY_SECRET: ${{ secrets.S3_ACCESS_KEY_SECRET }}
          DEST_DIR: 'sb.js/'
          SOURCE_DIR: 'docs'